### ISSUE TITLE
Allow flats to be expressed as sharps

### ISSUE THREAD

**Issue by justinlawrence** [nolanlawson/chord-magic#3] opened 2018-05-31 16:16 UTC
We were keen to use this library, but could not have a D/F# chord expressed as D/Gb.

Might be worth adding as another language? Perhaps "English-Sharp".

**Comment by nolanlawson** [comment] 2018-06-01 15:57
duplicate of #1, yes there should be more options to choose sharps vs flats etc

**Closed as completed by nolanlawson** 2018-06-01 15:57 UTC

**Comment by nolanlawson** [comment] 2018-06-02 04:47
Custom note namings are now supported and published in v2.1.0. Thanks for the suggestion!

**Comment by justinlawrence** [comment] 2018-06-02 06:52
Thanks Nolan!!
